### PR TITLE
Watch feature

### PR DESCRIPTION
**Pull request by jwu910**
@rainrivas

### CODE REVIEW

**Review by rainrivas — APPROVED** [review]

**Comment by jwu910** [comment]
Thanks @rainrivas

**Comment by rainrivas** [comment]
will you be deleting watch feature or going to keep working on it?

**Comment by jwu910** [comment]
I think there is more to be added to the watch feature. I need to add multiple directoreis to be watched

**Comment by jwu910** [comment]
test

**Comment by jwu910** [comment]
twst 2

**Pull request merged**
