### PR TITLE
Update "tests"

### PR DESCRIPTION
**Pull request by jwu910**

### CODE REVIEW

**Review by AlChiu — APPROVED** [review]

**Comment by phuchle** [comment]
@jwu910 Your tests would benefit from having a structure like:

* set up some conditions
* simulate doing something in your code
* asserting on expected outcomes

A testing framework would help you.

**Comment by jwu910** [comment]
Thanks Phuc! I'll look into some.

**Comment by jwu910** [comment]
@rainrivas  @phuchle  @AlChiu @psyduc 

Test file has been updated. Currently only 1 test. Create as many files as indicated by user and check for appropriate file names within save folder and watch folders.

**Review by phuchle — APPROVED** [review]
@jwu910  Looks good to me.  I think this covers the functionality of what you're trying to do so far.  More tests can be added in the future when you implement more features.

**Comment by jwu910** [comment]
Thanks. I still need to get the print stuff set up. once that gets done, we can test to see if print files get 'printed'

**Pull request merged**
