### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rainrivas**
Fixing a previous merge conflict

### CODE REVIEW

**Comment by rainrivas** [comment]
@jwu910 you should be able to merge FF this change (I think that would be a "rebase and merge" in GH terms)

**Review by jwu910 — CHANGES_REQUESTED** [review]
Lines 7-10 are also unnecessary. Technologies used section should be removed. I just changed it to libraries, since they're libraries. lol

**Review by jwu910 — APPROVED** [review]
Looks good. Haha thanks.

Let's chat soon about managing product releases.

**Comment by rainrivas** [comment]
@jwu910 lets meet up ... tomorrow? Also don't forget to close and merge this PR and Issue

**Comment by jwu910** [comment]
Thanks @rainrivas .

Dinner and light badminton? See if Diane is free?

**Pull request merged**
